export default Object.freeze({
  AUTH_NAVIGATION: "Auth Nav",
  AUTH_WELCOME_SCREEN: "Welcome Screen",
  AUTH_LOGIN_SCREEN: "Login Screen",
  AUTH_REGISTER_SCREEN: "Register Screen",

  BTAB_NAVIGATION: "Bottom Tab Nav",
  BTAB_HOME_SCREEN: "Home Screen",
  BTAB_ACCOUNT_SCREEN: "Account Screen",
  BTAB_ACTION_SCREEN: "Actions Screen",

  USER_NAVIGATION: "User Nav",
  USER_CHANGE_PWD_SCREEN: "Change Password",
  USER_CHANGE_PROFILE_UPDATE_SCREEN: "Update Profile",
  USER_DEFAULT_SCREEN: "Default Profile",
  USER_CREATE_PROFILE_SCREEN: "Create Profile",
  USER_ACCOUNT_VERIFY_SCREEN: "AccountVerificationForm Screen",
  USER_SETTINGS_SCREEN: "Settings Screen",

  PERMISIONS_NAVIGATION: "Permisions Nav",
  PERMISIONS_MENU_SCREEN: "PermisionsMenuScreen",
  PERMISION_ROLES_SCREEN: "Roles Screen",
  PERMISIONS_ROLE_FORM_SCREEN: "RolesForm Screen",
  PERMISIONS_ROLE_DETAIL_SCREEN: "Roles Detail Screen",

  PERMISIONS_PRIVILEGES_SCREEN: "Privileges Screen",
  PERMISIONS_PRIVILEGE_DETAIL_SCREEN: "PrivilegeDetail Screen",
  PERMISIONS_PRIVILEGE_FORM_SCREEN: "PrivilegeForm Screen",

  PERMISIONS_MENU_OPTIONS_SCREEN: "MenuOptions Screen",
  PERMISIONS_MENU_OPTION_DETAIL_SCREEN: "MenuOptionDetail Screen",
  PERMISIONS_MENU_OPTION_FORM_SCREEN: "MenuOptionForm Screen",

  PERMISIONS_SMS_CONFIG_FORM_SCREEN: "SMSConfigForm Screen",
  PERMISIONS_SMS_CONFIG_SCREEN: "SMSConfig Screen",

  PERMISIONS_USER_ROLES_SCREEN: "UserRoles Screen",
  PERMISIONS_USER_ROLES_ASSIGNMENT_SCREEN: "UserRolesAssignment Screen",

  ART_NAVIGATION: "ARTNav",
  ART_MODELS_SCREEN: "ARTModels Screen",
  ART_MODELS_FORM_SCREEN: "ARTModelsForm Screen",

  ART_GROUP_LEADS_FORM_SCREEN: "ARTGroupLeadsForm Screen",
  ART_GROUP_LEADS_SCREEN: "ARTGroupLeads Screen",
  ART_GROUP_LEAD_DETAIL_SCREEN: "ARTGroupLeadDetail Screen",

  ART_GROUPS_FORM_SCREEN: "ARTGroupForm Screen",
  ART_GROUP_SCREEN: "ARTGroup Screen",
  ART_GROUP_DETAIL_SCREEN: "ARTGroupDetail Screen",
  ART_GROUP_ADD_NEW_MEMBER_FORM_SCREEN: "ARTGroupAddNewMember Screen",

  ART_DISTRIBUTION_EVENTS_FORM_SCREEN: "ARTDistributionEventForm Screen",
  ART_DISTRIBUTION_EVENTS_SCREEN: "ARTDistributionEvent Screen",
  ART_DISTRIBUTION_EVENTS_DETAIL_SCREEN: "ARTDistributonDetail Screen",
  ART_DISTRIBUTION_EVENTS_SERVICE_FORM_SCREEN:
    "DistributionEventServiceForm Screen",

  ORDERS_NAVIGATION: "Orders Nav",
  ORDERS_APPOINMENTS_SCREEN: "AppointmentsScreen",
  ORDERS_APPOINMENT_DETAIL_SCREEN: "AppointmentDetailScreen",
  ORDERS_UPCOMING_APPOINMENTS_SCREEN: "UpcomingAppointmentScreen",
  ORDERS_DELIVERY_MODES_SCREEN: "DeliveryModes Screen",
  ORDERS_DELIVERY_MODES_FORM_SCREEN: "DeliveryModesfORM Screen",

  ORDERS_ORDERS_SCREEN: "Orders Screen",
  ORDERS_ORDER_DETAIL_SCREEN: "OrderDetail sCREEN",
  ORDERS_PATIENT_ORDER_FORM_SCREEN: "PatientOrderForm Screen",
  // ORDERS_PROVIDOR_DISPENSE_DRUGS_FORM_SCREEN: "DispenseDrugForm Screen",

  ORDERS_DELIVERY_FEEDBACK_FORM_SCREEN: "DeliveryFeedBackForm Screen",

  ORDERS_DELIVERY_TIMESLOTES_SCREEN: "DeliveryTimeSlot Screen",
  ORDERS_DELIVERY_TIMESLOTES_FORM_SCREEN: "DeliveryTimeSlotForm Screen",

  ORDERS_DELIVERY_METHODSS_SCREEN: "DeliveryMethods Screen",
  ORDERS_DELIVERY_METHOD_FORM_SCREEN: "DeliveryMethodForm Screen",

  ORDERS_PROVIDOR_DELIVERY_REQUESTS_SCREEN: "DeliveryRequests Screen",
  ORDERS_PROVIDOR_DELIVERY_HISTORY_SCREEN: "DeliveryHistory Screen",
  ORDERS_PROVIDOR_DELIVERY_DETAIL_SCREEN: "DeliveryDetail Screen",
  ORDERS_PROVIDOR_DELIVERY_TRUCK_SCREEN: "DeliveryTruck Screen",
  ORDERS_PROVIDOR_DISPENSE_DRUGS_SCREEN: "DispenseDrugs Screen",
  ORDERS_PROVIDOR_DISPENSE_DRUGS_DETAIL_SCREEN: "DispenseDrugsDetail Screen",

  ORDERS_ORDER_FOR_ANOTHER_SCREEN: "OrderForAnother Screen",
  ORDERS_ORDER_FOR_ANOTHER_FORM_SCREEN: "OrderForAnotherForm Screen",

  TREATMENT_SURPORT_NAVIGATION: "tSurport Nav",
  TREATMENT_SURPORT_SCREEN: "TreatmentSurporters Screen",
  TREATMENT_SURPORT_PROVIDOR_FORM_SCREEN: "TreatmentSurporteForm Screen",
  TREATMENT_SURPORT_MY_SURPORTERS_FORM_SCREEN: "MyTreatmentSurport Screen",
  TREATMENT_SURPORT_CAREGIVER_FORM_SCREEN: "CareGiverForm Screen",
  TREATMENT_SURPORT_CARERECEIVER_FORM_SCREEN: "CareReceiverForm Screen",
  TREATMENT_SURPORT_DETAIL_SCREEN: "TreatmentSurportDetail Screen",
  TREATMENT_SURPORT_ACCEPT_INVITE_SCREEN: "AcceptInvitation Screen",

  CHATS_NAVIGATION: "ChatsNav Screen",
  CHATS_CONVERSATION_SCREEN: "ChatsDetailScreen Screen",
});
